"""MobileNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jhe0JeJBieD0J13K41fvEBX_FIcbQk0x
"""

!pip install pdf2image
!apt-get install poppler-utils -y

from google.colab import files
import os

print("Upload REAL certificates (PDF or Image)")
real_uploaded = files.upload()

os.makedirs("dataset/real", exist_ok=True)

print("Upload FAKE certificates (PDF or Image)")
fake_uploaded = files.upload()

os.makedirs("dataset/fake", exist_ok=True)

from pdf2image import convert_from_path
import shutil

def process_files(uploaded_files, label_folder):
    for file_name in uploaded_files.keys():

        if file_name.endswith(".pdf"):
            pages = convert_from_path(file_name, dpi=200)
            for i, page in enumerate(pages):
                save_path = f"dataset/{label_folder}/{file_name[:-4]}_{i}.jpg"
                page.save(save_path, "JPEG")

        elif file_name.lower().endswith((".png", ".jpg", ".jpeg")):
            shutil.move(file_name, f"dataset/{label_folder}/{file_name}")

# Process real files
process_files(real_uploaded, "real")

# Process fake files
process_files(fake_uploaded, "fake")

print("Files processed successfully!")

print("Real Images:", len(os.listdir("dataset/real")))
print("Fake Images:", len(os.listdir("dataset/fake")))

import tensorflow as tf

IMG_SIZE = 224
BATCH_SIZE = 16

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "dataset",
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)

val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "dataset",
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)

# Normalize
train_ds = train_ds.map(lambda x, y: (x/255.0, y))
val_ds = val_ds.map(lambda x, y: (x/255.0, y))

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models

base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3)
)

base_model.trainable = False  # Freeze base

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(1, activation='sigmoid')
])

model.summary()

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10
)

loss, accuracy = model.evaluate(val_ds)
print("Validation Accuracy:", accuracy)

from google.colab import files
from tensorflow.keras.preprocessing import image
import numpy as np

print("Upload certificate to test")
uploaded_test = files.upload()

test_image_path = list(uploaded_test.keys())[0]

img = image.load_img(test_image_path, target_size=(224,224))
img_array = image.img_to_array(img) / 255.0
img_array = np.expand_dims(img_array, axis=0)

prediction = model.predict(img_array)

print("Raw Prediction:", prediction[0][0])

if prediction[0][0] > 0.5:
    print("Prediction: REAL Certificate ✅")
else:
    print("Prediction: FAKE Certificate ❌")

from google.colab import files
from tensorflow.keras.preprocessing import image
import numpy as np

print("Upload certificate to test")
uploaded_test = files.upload()

test_image_path = list(uploaded_test.keys())[0]

img = image.load_img(test_image_path, target_size=(224,224))
img_array = image.img_to_array(img) / 255.0
img_array = np.expand_dims(img_array, axis=0)

prediction = model.predict(img_array)

print("Raw Prediction:", prediction[0][0])

if prediction[0][0] > 0.5:
    print("Prediction: REAL Certificate ✅")
else:
    print("Prediction: FAKE Certificate ❌")

